### ISSUE TITLE
Error al activar el caf

### ISSUE THREAD

**Issue by kkoci** [odoo-chile/l10n_cl_dte_caf#4]
Hola, buenas noches

Estaba probando el módulo con un Folio, lo sube, todo bien, pero al tratar de activarlo me lanza éste error:

`File "/home/usuario/odoov9/odoo-9.0c-20160712/openerp/addons/l10n_cl_dte_caf/models/caf.py", line 99, in action_enable
    elif self.rut_n != self.company_id.vat.replace('L0','L'):
AttributeError: 'bool' object has no attribute 'replace'`

¿Esta ésto relacionado con Letras contables o algo así? No entiendo muy bien

Gracias de antemano

**Comment by Danisan** [comment]
El error se debe a que el vat de la compañía está vacío (False).

La forma más fácil de hacerlo es ir a la empresa asociada a la compañía e ingresar el RUT. Esto genera automáticamente el VAT en el partner, y lo copia a la compañía.

Caso contrario en el campo vat de la compañía, le ingresas "CL" con el rut sin guiones ni puntos.

**Comment by kkoci** [comment]
@Danisan muchas gracias, efectivamente éso era, ahora me habla de un numero que debe ser igual al del CAF, éso lo chequeo yo ahora a ver, Gracias de nuevo
